[package]
name = "Financial-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.0", features = ["bundled"] }
dirs = "4.0.0"
clap = { version = "4.0", features = ["derive"] }
